### ISSUE TITLE
Rendering difference between Windows and Ubuntu

### ISSUE THREAD

**Issue by hchoi405** [compix/VoxelConeTracingGI#2]
While migrating to Ubuntu, I found that there is a big difference at GI rendering result as you can see from the two images below. I used the same code and configurations, hardware and no error appears in the output.

![linux](https://user-images.githubusercontent.com/43630902/68302555-a42aca80-00e5-11ea-8a10-7f72a01420bf.png)
<img width="826" alt="windows" src="https://user-images.githubusercontent.com/43630902/68302558-a5f48e00-00e5-11ea-88cc-b3455b13f752.png">

I'm still trying to figure out what's the causes of this problem. Any comments would be helpful.

Thank you.

**Comment by hchoi405** [comment]
Solved it, but don't know exactly what was the cause

The problem was the order of the G-buffer texture attachment to a frame buffer.

For my case, I changed it from 
albedo -> normal -> specular -> emission 
to 
specular -> emission -> normal -> albedo

(in the constructor of `SceneGeometryPass.cpp`)

**Comment by compix** [comment]
Hi hchoi405,

sorry for the late response. I checked the problem today and found the cause of the problem in the framebuffer where the order was dependent on an unordered map which will obviously fail based on different implementations. 

The fix is on the master branch.
