### ISSUE TITLE
Missing define

### ISSUE THREAD

**Issue by e2002e** [compix/VoxelConeTracingGI#5]
Hi, size_t is missing when compiling, you need to include <cstddef> into Pool.cpp

**Comment by compix** [comment]
Hi, thank you for the report. I changed size_t to std::size_t and included cstddef in the whole project. This is more appropriate for C++ and should be compiler independent now. The fix is in a12f7c9e20f0dec687742f19737a3b9e84ca78cc

**Comment by e2002e** [comment]
Can you help me with code for GI ? It's for armory3d.
I'm leaving you my email here since it's a closed issue: yvain29@gmail.com

**Comment by compix** [comment]
Hi, I have sent you an email. I recommend you edit out your email address to avoid potential spam mail.

**Comment by e2002e** [comment]
Just sagged you !!!!!
