### ISSUE TITLE
Failed to build on MSYS2 MINGW64

### ISSUE THREAD

**Issue by ghost** [compix/VoxelConeTracingGI#6]

**Comment by compix** [comment]
Hi, thanks for the report however I'm currently busy with another project and not planning to support MINGW64 if it doesn't work already. I can only confirm that it's running with Visual Studio (Community) 2015 or newer on Windows 8 + 10 and GCC 7.4.0 on Ubuntu.

However if you identify the issue it would be nice if you submit a pull request for the fix.
